### ISSUE TITLE
Please update your parts in updated specification

### ISSUE THREAD

**Issue by ddxxdd-code** [CSC207-UofT/course-project-group-002-tut5101#34]
I have uploaded the updated specification to DESIGN_DOCUMENT.md, please check whether your parts are expressed precisely in the specification, thank you!
The issue is that I don't know whether the class manager has implemented all the functionalities described in the specification.
Specification is copied from our shared file.
Please check!

**Comment by dabandaidai** [comment]
Yes we are working on it.

**Comment by ShaojieDong503** [comment]
Inventory part is expressed

**Comment by MeeskaM00ska** [comment]
Review part is expressed precisely in the specification

**Comment by evelyn323** [comment]
Customer specification for placing orders is correct

**Comment by alekao** [comment]
Kitchen specification is now correct and precise.

**Comment by Chan-Y** [comment]
Updated the Manager functionalities described in the specification.
