### ISSUE TITLE
Delivery Staff UI showing extra information

### ISSUE THREAD

**Issue by alekao** [CSC207-UofT/course-project-group-002-tut5101#42]
The view order functionality for delivery staff currently shows extra information such as the ingredients of each dish, please remove to give the delivery staff just enough information to delivery.

**Comment by alekao** [comment]
Also, the address of the order is not shown for the delivery staff right now, please add

**Comment by ddxxdd-code** [comment]
Fixed issue #42 "Delivery Staff UI showing extra information" by adding method getOrderContent to Order, change the call to getOrderContent in DeliverOrder. 

Tested using TempKitchenMain.main(), it shows only destination, dish names and quantities in the UI of delivery staff. Whole program runs normally.

Running result:
<img width="455" alt="Screen Shot 2021-11-03 at 22 25 37" src="https://user-images.githubusercontent.com/65443542/140247334-3a4deef5-686b-4534-957d-1aa3c96d47a3.png">
