### ISSUE TITLE
Serving Staff and Delivery Staff UI get new dish/order every time the user views the dish/order.

### ISSUE THREAD

**Issue by alekao** [CSC207-UofT/course-project-group-002-tut5101#43]
Currently, every time the serving staff or delivery views its dish/order to be served/delivery, the UI gets a new one from the buffer, which shouldn't be happening. A design more similar to the GUI implementation of these two UI are recommended. Reference Kitchen UI if needed.

**Comment by ddxxdd-code** [comment]
Investigating.
Probably tomorrow will fix it.

**Comment by ddxxdd-code** [comment]
New feature added. Add action view current order/dish to staffUIs, now distinguish the action of view current and get next that view current tries to get information of the current dish/order a staff is carrying while get next tries to get a new dish/order when there is none at hand.
